spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nekperu15739/config-repo
server:
  port: 8888
  
management:
  security:
    enabled: false
    
logging:
  path: /tmp
  